#!/usr/bin/python3

# Copyright (c) 2019, SUSE LLC, All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library.

"""Switch any RIS service registered to the update infrastructure to
   a plugin based service"""

import os

import cloudregister.registerutils as utils

old_service_plugin = '/usr/lib/zypp/plugins/services/cloud_update'
if os.path.exists(old_service_plugin):
    os.unlink(old_service_plugin)

utils.switch_services_to_plugin()
