.\" Process this file with
.\" groff -man -Tascii cloudguestregstryauth.1
.\"
.TH cloudguestregstryauth.1
.SH NAME
cloudguestregstryauth \- Refresh registry credentials for a registered SUSE Linux Enterprise instance
.SH SYNOPSIS
.B cloudguestregstryauth
.SH DESCRIPTION
.B cloudguestregstryauth
Refresh registry credentials for a registered SUSE Linux Enterprise instance. The client will reach
out to the already configured update server to refresh the existing credentials.
