name: CI-Code-Style

on: [push]

jobs:
  unit_tests:
    name: Unit tests for cloud regionsrv client
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.13"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
      - name: Run flake checks
        run: make check
        env:
          PY_VER: ${{ matrix.python-version }}
      - name: Run pytest
        run: make test
        env:
          PY_VER: ${{ matrix.python-version }}
